### ISSUE TITLE
Minimize WASM size

### ISSUE THREAD

**Issue by MartinKavik** [seed-rs/seed-quickstart-webpack#9]
- https://www.codeslow.com/2019/12/tiny-windows-executable-in-rust.html
- https://github.com/johnthagen/min-sized-rust

What can be added into `Cargo.toml`:
```toml
[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
```
Other ideas?

@TatriX - you (will) have the project based on the current `seed-quickstart-webpack` template - I would be glad if you can confirm, that it helps or if you find other options. Don't hurry, I plan to integrate it to next release without ETA. Thanks!
